import type * as monaco from 'monaco-editor';

const theme = {
  id: 'ayu-dark',
  name: 'Ayu Dark',
  uiClass: 'theme-ayu-dark',
  cssVars: {
    '--bg-app': '#0a0e14',
    '--bg-elevated': '#141920',
    '--bg-subtle': '#0f1419',
    '--bg-muted': '#1c2433',
    '--bg-strong': '#242e42',
    '--text-primary': '#bfbdb6',
    '--text-secondary': '#acaba6',
    '--text-tertiary': '#5c6773',
    '--text-muted': '#4d5566',
    '--text-faint': '#1c2433',
    '--border-subtle': '#141920',
    '--border-default': '#1c2433',
    '--border-strong': '#242e42',
    '--scrollbar-thumb': '#1c2433',
    '--scrollbar-hover': '#242e42',
    '--statusbar-bg': '#0f1419',
    '--statusbar-border': '#141920',
    '--tabbar-bg': '#0a0e14',
  },
  data: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '5c6773', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'ff7733' },
      { token: 'string', foreground: 'aad94c' },
      { token: 'number', foreground: 'f29e74' },
      { token: 'regexp', foreground: '95e6cb' },
      { token: 'type', foreground: '39bae6' },
      { token: 'class', foreground: '39bae6' },
      { token: 'function', foreground: 'f07178' },
      { token: 'variable', foreground: 'bfbdb6' },
      { token: 'constant', foreground: 'f29e74' },
      { token: 'identifier', foreground: '59c2ff' },
      { token: 'operator', foreground: 'f29668' },
      { token: 'delimiter', foreground: 'bfbdb6' },
      { token: 'tag', foreground: '39bae6' },
      { token: 'attribute', foreground: 'ffb454' },
      { token: 'annotation', foreground: '39bae6' } 
    ],
    colors: {
      'editor.background': '#0a0e14',
      'editor.foreground': '#bfbdb6',
      'editor.lineHighlightBackground': '#141920',
      'editorLineNumber.foreground': '#5c6773',
      'editor.selectionBackground': '#273747',
      'editorCursor.foreground': '#ff8f40',
      'editor.inactiveSelectionBackground': '#1b2733',
      'editorWidget.background': '#0f1419',
      'editorWidget.border': '#1c2433',
      'input.background': '#0a0e14',
      'input.border': '#1c2433',
      'focusBorder': '#ff8f40',
    },
  } as monaco.editor.IStandaloneThemeData,
};

export default theme;