import type * as monaco from 'monaco-editor';

const theme = {
  id: 'dark-protocol',
  name: 'Dark Protocol',
  uiClass: 'theme-dark-protocol',
  cssVars: {
    '--bg-app': '#0f1015',
    '--bg-elevated': '#181920',
    '--bg-subtle': '#13141a',
    '--bg-muted': '#242732',
    '--bg-strong': '#525560',
    '--text-primary': '#f8f9fa',
    '--text-secondary': '#e5e7eb',
    '--text-tertiary': '#8b8d98',
    '--text-muted': '#525560',
    '--text-faint': '#242732',
    '--border-subtle': '#13141a',
    '--border-default': '#242732',
    '--border-strong': '#525560',
    '--scrollbar-thumb': '#242732',
    '--scrollbar-hover': '#525560',
    '--statusbar-bg': '#13141a',
    '--statusbar-border': '#181920',
    '--tabbar-bg': '#13141a',
  },
  data: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '8b8d98', fontStyle: 'italic' },
      { token: 'keyword', foreground: '05d671', fontStyle: 'bold' },
      { token: 'string', foreground: '86efac' },
      { token: 'number', foreground: 'f7931a' },
      { token: 'regexp', foreground: 'f7931a' },
      { token: 'type', foreground: 'f8f9fa', fontStyle: 'bold' },
      { token: 'class', foreground: 'f8f9fa', fontStyle: 'bold' },
      { token: 'function', foreground: '05d671' },
      { token: 'variable', foreground: 'e5e7eb' },
      { token: 'constant', foreground: 'f7931a' },
      { token: 'identifier', foreground: 'f8f9fa' },
      { token: 'operator', foreground: '8b8d98' },
      { token: 'delimiter', foreground: '8b8d98' },
      { token: 'tag', foreground: '05d671' },
      { token: 'attribute', foreground: 'e5e7eb' },
    ],
    colors: {
      'editor.background': '#0f1015',
      'editor.foreground': '#f8f9fa',
      'editor.lineHighlightBackground': '#181920',
      'editorLineNumber.foreground': '#525560',
      'editor.selectionBackground': '#242732',
      'editorCursor.foreground': '#05d671',
      'editor.inactiveSelectionBackground': '#181920',
      'editorWidget.background': '#13141a',
      'editorWidget.border': '#242732',
      'input.background': '#0f1015',
      'input.border': '#242732',
      'focusBorder': '#05d671',
    },
  } as monaco.editor.IStandaloneThemeData,
};

export default theme;
