import type * as monaco from 'monaco-editor';

const theme = {
  id: 'dobri-next-a00-black',
  name: 'Dobri Next -A00- Black',
  uiClass: 'theme-dobri-black',
  cssVars: {
    '--bg-app': '#000000',
    '--bg-elevated': '#0a0a0a',
    '--bg-subtle': '#050505',
    '--bg-muted': '#111111',
    '--bg-strong': '#222222',
    '--text-primary': '#b0b6c4',
    '--text-secondary': '#8b92a5',
    '--text-tertiary': '#666d80',
    '--text-muted': '#444a59',
    '--text-faint': '#222222',
    '--border-subtle': '#0a0a0a',
    '--border-default': '#111111',
    '--border-strong': '#222222',
    '--scrollbar-thumb': '#222222',
    '--scrollbar-hover': '#333333',
    '--statusbar-bg': '#000000',
    '--statusbar-border': '#111111',
    '--tabbar-bg': '#000000',
  },
  data: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '4a6b63', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'c678dd' },
      { token: 'string', foreground: '4a6b63' },
      { token: 'number', foreground: 'f47067' },
      { token: 'regexp', foreground: 'f47067' },
      { token: 'type', foreground: '61afef' },
      { token: 'class', foreground: 'e5b567' },
      { token: 'function', foreground: 'e5b567' },
      { token: 'support.function', foreground: '2bbac5' },
      { token: 'variable', foreground: 'b0b6c4' },
      { token: 'variable.parameter', foreground: 'eb606b' },
      { token: 'constant', foreground: 'f47067' },
      { token: 'identifier', foreground: 'b0b6c4' },
      { token: 'operator', foreground: 'b0b6c4' },
      { token: 'delimiter', foreground: 'b0b6c4' },
      { token: 'tag', foreground: 'c678dd' },
      { token: 'attribute', foreground: 'eb606b' },
      { token: 'annotation', foreground: 'e5b567' } 
    ],
    colors: {
      'editor.background': '#000000',
      'editor.foreground': '#b0b6c4',
      'editor.lineHighlightBackground': '#0a0a0a',
      'editorLineNumber.foreground': '#444a59',
      'editor.selectionBackground': '#222222',
      'editorCursor.foreground': '#e5b567',
      'editor.inactiveSelectionBackground': '#111111',
      'editorWidget.background': '#050505',
      'editorWidget.border': '#111111',
      'input.background': '#000000',
      'input.border': '#111111',
      'focusBorder': '#e5b567',
    },
  } as monaco.editor.IStandaloneThemeData,
};

export default theme;